import { useParams } from "react-router-dom";
import { useQuery } from "@tanstack/react-query";
import { supabase } from "@/integrations/supabase/client";

export default function SharedExport() {
  const { id } = useParams<{ id: string }>();

  const { data: exportData, isLoading } = useQuery({
    queryKey: ["shared-export", id],
    queryFn: async () => {
      if (!id) return null;
      const { data, error } = await supabase
        .from("shared_exports")
        .select("*")
        .eq("id", id)
        .single();
      if (error) throw error;
      return data;
    },
    enabled: !!id,
  });

  if (isLoading) {
    return (
      <div className="flex min-h-screen items-center justify-center bg-background">
        <div className="animate-pulse text-muted-foreground">Loading...</div>
      </div>
    );
  }

  if (!exportData) {
    return (
      <div className="flex min-h-screen items-center justify-center bg-background">
        <p className="text-muted-foreground">Export not found</p>
      </div>
    );
  }

  return (
    <div className="flex min-h-screen items-center justify-center bg-background p-4">
      <div className="max-w-[1200px] w-full">
        <img
          src={exportData.image_url}
          alt={`${exportData.portfolio_name} Portfolio Report`}
          className="w-full rounded-xl shadow-2xl"
        />
        <p className="text-center text-muted-foreground text-sm mt-4">
          {exportData.portfolio_name} • Generated by Chess
        </p>
      </div>
    </div>
  );
}
