
INSERT INTO public.brokers (name, country, category, display_order) VALUES
('IEB+', 'AR', 'digital', 1),
('IOL (InvertirOnline)', 'AR', 'digital', 2),
('Balanz', 'AR', 'digital', 3),
('Bull Market Brokers', 'AR', 'digital', 4),
('PPI (Portfolio Personal)', 'AR', 'digital', 5),
('Cocos Capital', 'AR', 'digital', 6),
('Inviu', 'AR', 'digital', 7),
('TM Inversiones', 'AR', 'traditional', 8),
('Allaria Ledesma', 'AR', 'traditional', 9),
('SBS Trading', 'AR', 'traditional', 10),
('TPCG Valores', 'AR', 'traditional', 11),
('Bancos Comerciales', 'AR', 'traditional', 12),
('Rava Bursátil', 'AR', 'specialized', 13),
('EcoValores', 'AR', 'specialized', 14),
('Nexo', 'AR', 'specialized', 15),
('Interactive Brokers', 'US', 'digital', 1),
('Charles Schwab', 'US', 'digital', 2),
('Fidelity', 'US', 'digital', 3),
('TD Ameritrade', 'US', 'digital', 4),
('Robinhood', 'US', 'digital', 5),
('E*TRADE', 'US', 'digital', 6),
('Otro', 'US', 'other', 99);
